import { NextRequest, NextResponse } from 'next/server';
import { requireAuthRead } from '@/lib/api-guard';
import { agentRouter } from '@/orchestrator';

// UUID v4 format — matches IDs generated by agentRouter.submit()
const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;

export async function GET(req: NextRequest) {
  const { error } = await requireAuthRead(req);
  if (error) return error;

  const { searchParams } = req.nextUrl;
  const rawTaskId = searchParams.get('taskId');

  if (rawTaskId) {
    if (!UUID_RE.test(rawTaskId)) {
      return NextResponse.json({ error: 'Invalid taskId format' }, { status: 400 });
    }

    const { taskStore } = await import('../submit/route');
    const task = taskStore.get(rawTaskId);

    if (!task) {
      return NextResponse.json({ error: 'Task not found' }, { status: 404 });
    }

    return NextResponse.json({ data: task });
  }

  // Live agent states from the orchestrator (Tech Doc §10 — AgentRouter.getAllStates())
  return NextResponse.json({
    data: {
      agents:    agentRouter.getAllStates(),
      queueSize: agentRouter.getQueueSize(),
      conflicts: agentRouter.getConflicts(),
      timestamp: new Date().toISOString(),
    },
  });
}
